#File: docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:13
    container_name: openroots-db
    environment:
      - POSTGRES_USER=yourUsername
      - POSTGRES_PASSWORD=yourPassword
      - POSTGRES_DB=openroots
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: openroots-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/openroots
      - SPRING_DATASOURCE_USERNAME=yourUsername
      - SPRING_DATASOURCE_PASSWORD=yourPassword
volumes:
  pgdata:
